/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafio3;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Cassia
 */
public class Desafio3Ed extends javax.swing.JFrame {
Float peso, altura, imc;
Image foto;
    /**
     * Creates new form Desafio3Ed
     */
    public Desafio3Ed() {
        initComponents();
    }
    
    public void imageIcon(){
        ImageIcon img = new ImageIcon(getClass().getResource("img.jpg"));
        
        jLab1.setIcon(img);
        

    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cx2 = new javax.swing.JTextField();
        cx1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cx3 = new javax.swing.JTextArea();
        jLab1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("CALCULO  DO IMC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 410, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("PESO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 80, 90, 40);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("ALTURA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 140, 140, 40);

        cx2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        cx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx2ActionPerformed(evt);
            }
        });
        getContentPane().add(cx2);
        cx2.setBounds(250, 140, 180, 40);

        cx1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        getContentPane().add(cx1);
        cx1.setBounds(250, 80, 180, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 130, 117, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("DESCUBRA SEU INDICE DE MASSA CORPORAL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 50, 320, 17);

        cx3.setColumns(20);
        cx3.setRows(5);
        jScrollPane1.setViewportView(cx3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 190, 190, 200);

        jLab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLab1);
        jLab1.setBounds(20, 190, 430, 200);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desafio3/capa.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        peso=Float.valueOf(cx1.getText());
        altura=Float.valueOf(cx2.getText());
        imc=peso/(altura*altura);
        cx3.setText(verificaIMC(imc));
        imageIcon();
    
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desafio3Ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desafio3Ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desafio3Ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desafio3Ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desafio3Ed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cx1;
    private javax.swing.JTextField cx2;
    private javax.swing.JTextArea cx3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLab1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private String verificaIMC(Float imc) {
        String result=null;
        
        if (imc <= 18.5 )
            result="MAGREZA"+"\n Seu IMC é de "+imc+".";
        
            
        else if (imc > 18.6 & imc <=24.9 )
            result="PESO NORMAL"+"\n Seu IMC é de "+imc+".";
           
            
        else if (imc > 25 & imc <=29.9 )
            result="SOBREPESO"+"\n Seu IMC é de "+imc+".";
        
        else if (imc > 30 & imc <=34.9 )
            result="OBESIDADE GRAU I"+"\n Seu IMC é de "+imc+".";
        
        else if (imc > 35 & imc <=39.9 )
            result="OBESIDADE GRAU II"+"\n Seu IMC é de "+imc+".";
        
        else 
            result="OBESIDADE GRAU III"+"\n Seu IMC é de "+imc+".";
            
        
        return result;
    }


   
}
